# done, submitted
def counter(inp: str) -> str:
    freq_list = [0, 0, 0, 0]
    for letter in inp:
        if letter == "A":
            freq_list[0] += 1
        elif letter == "C":
            freq_list[1] += 1
        elif letter == "G":
            freq_list[2] += 1
        elif letter == "T":
            freq_list[3] += 1
    return list_to_string(freq_list)


def list_to_string(ls: list) -> str:
    output = ""
    for element in ls:
        output += str(element) + " "
    return output[:-1]

a = "GCCATCATACTGACTTATACAAGGACGCGGTTAACTTCCGCAAAACGGCATCGTAACGCCTCTTCGTGTATGCTCTGTCTAAACTGCTCAGCATTTGATTGTGGGCTCACGAATGGTTAGACCGTTAAACAGGTCTTCAATCATTCACCATCCTCAGCACAGCTGTTCTATCCGCATACTCCGGAAACCCTCAAATAGTCGAATCCGACTGTTTCTCGCTCAGCTGTATACTCGTCCTGTGGCCTCTGACTCGTATCTCTGACACGTTCATCCCTATGTTTCATTCCAATGCGACATGCGTGAACCTCTTGGATTCCGGGTAGTAGGGCAACCGCAAGGTCTTGGCCCGGTCTGGCTCGTGACCCCCGGTTTAGAACCAAGAGCAATACGACGTTAACACATGGTGATATACGTTTTAAGCGATACTTTCGTAACTATTCCGAGTTTGATGATCATTATTCACGTTCTATTGCTGTAAAAAAGCTGGGGACGTATGCCCTGAGGCTTGACATGAGGACCTGGACCGCTACGAGAACATTGTCCGTCCCGGGATCGGGCGATTTGACAATGGGGCGGAAGATGGACGCAGCATTAATACTCTCTTAGACTAATCCCTGAGCAAGTGGTGGGTTTTCGCCGCTAATTGCCCAGAAAAAATTCCGCCGAACATCAGACGGCACAGACCTCCGTTTCGAGCAAAGCAAAATTCTTGGCCTTCCTTATGAGCAGCCAAGGGGCCACGGGTTTAAGATTCAACCACAGTAGCATACGAGGTGACATTTTAGTCCTTATCTGTGGACCGGTGATTGCATCGGGCGATAAACAAGTTTCTTCGCTGGCCTGTGATTGCGCTTGCACTGACCTGTTCCGACCCCAGGGCCGCAGC"
print(counter(a))
