# done and submitted
def main(inp):
    output = ""
    reversed = inp[::-1]
    for letter in reversed:
        if letter == "A":
            output += "T"
        elif letter == "T":
            output += "A"
        elif letter == "C":
            output += "G"
        elif letter == "G":
            output += "C"
    return output

a = "AAAACCCGGT"
# print(main(a) == "ACCGGGTTTT")

b = "TTGATCTTCAGTTAATTTTTAAAGTTTGTGGGGTACGGAGCTATATGTCCGGGCCGCTGATTCTTGGAACTCGGTCCTTCGCCCAGACTTGAGCGGCATATAGCACTGCGTTCACAGCGGTTATGTATCGTATAGACCACCAGCGAATCTTACGGGTCACGGCGTGCGTTAGTCCTCGATTAGGCGAAATCTATCACGGCAACGAGTAGAATCGTTTCCCCACGAGTATATCACGTGCCCGGGCTAGCCCGATACGTTTTAACACTTTTACTGCTGTCGTATAAGTATTTTGCCGCGCCAGTCTGCCCTGTTCCGATGTCCTCTCGAGTCTTGCTGAACAAAGCCTGTATTTCGTCGTCACGAGGGGTAAGTTTCCCCGGTAAACGAATCCTGAAAAAACGCTTTACAGTACACCCGTCGGGGCATTAGGCAATACCAACATAGGTTTTTCTTATTCCAACTAAACTAACACCATAAGAGCAAGTCAGGTACAATAGTGCTCGATAGGCCTCGTCCCATCGGACAAAGTGCTACGCCAAGTTATCCGTCCGTTAATACTTTGGTGCGTTCGTCAACTAAAACTGCCGCTCGCTGCGCAGTATCCAAGTTCAGAGATTTCATACTCCAAAAAACTTGAGTACAACAATAACCTACGTCGGTGTTGTGACTTGTATGAGAGTCTCTTGGTTGTGTAGGCCGCTAACCACTAGGGGCACCTTGTTATTGCGTAACTTGCTGCGCAGTAAAATTAGGCCTAGAATATGATGGAAGTTTGAAGATAGGGGCGTAATACGCGTCATGCGTGACACACACCTCCCCGGTGGCGACACCTGTCGCAGGACTCTGACGGTAGCATAGGTTATTGGGTTGCTC"
print(main(b))