# done and submitted
def subs(long: str, sub: str) -> str:
    answers = []
    for letter_index in range(len(long) - len(sub)):
        current_mini = ""
        for i in range(len(sub)):
            current_mini += long[letter_index + i]
        # print(current_mini)
        if current_mini == sub:
            answers.append(letter_index + 1)  # +1 for human reading
    # print(answers)
    return list_to_string(answers)


def list_to_string(ls: list) -> str:
    output = ""
    for element in ls:
        output += str(element) + " "
    return output[:-1]

# print(subs("GATATATGCATATACTT", "ATAT"))
a = "GCGTTTGGCGTTTGAGCGTTTGACAAGGAAAACGCCGTCGCGTTTGGAGTGCGTTTGTCGGCGTTTGTTCTTGGTTGCGTTTGCGTCGGGCGTTTGGCGTTTGATGGTACGCGTTTGGGACGTTAGGCGTTTGGCGTTTGCTAGCGTTTGTTTTCACAAGACCGCTAAGTCTTCGGCGTTTGAGCGTTTGGCGTTTGGCGTTTGCTAGCGTTTGTGCGTTTGGCGTTTGCGCCGCGTTTGTTGGCGTTTGGCGTTTGGCGTTTGCATGCGTTTGACCAAGGGCGTTTGCGCGTTTGGCGTTTGGCGTTTGGGCGTTTGGCGTTTGGCGTTTGGGCGTTTGGCGTCAGCGTTTGCGCGTTTGCCAGCGTTTGCGCGTTTGAGCGTTTGGAGGCGTTTGGCGTTTGTGCGTTTGGGCTGCGTTTGGGCGTTTGCGCGTTTGGCGTTTGACCGCGTTTGGCGTTTGATCAGGCTGCTGGCGTTTGGCGTTTGCGCGTTTGGCGTTTGCGCGTTTGAAGGCGTTTGGCGTTTGCCCTAAAGTCGGTGCGTTTGGTCGCGTTTGCTGCCGTGCGTTTGTGGCGTTTGACGCGTTTGGGCGTTTGCGCGTTTGAGCGTTTGAGCGTTTGGGGCGTTTGGAGAACGCGTTTGATATCCGGCCGGCGTTTGGGCTGCGTTTGCAAGGCGTTTGCTAATTGCGTTTGGGCGTTTGTGCGTTTGTTGCGTTTGGCGTTTGGGCGTTTGGCGTTTGTCGCTATTGAGCGTTTGCCGCGTTTGCTCGGCGTTTGGCGTTTGCCGCGTTTGCATCTGCGTTTGGCGTTTGGCGTTTGAAGCGTTTGTGCGTTTGATTC"
b = "GCGTTTGGC"
print(subs(a, b))